version: "3.3"
services:
  backend:
    container_name: finpong-backend
    image: mertkoroglu/finpong:backend
    restart: unless-stopped
    ports: 
        - 3002:3002
        - 4000:4000
    networks:
        - internal
  frontend:
    container_name: finpong-frontend
    image: mertkoroglu/finpong:frontend
    restart: unless-stopped
    ports:
        - 3000:3000
    depends_on:
        - backend
    networks:
        - internal
networks:
    internal: