version: "3.3"
services:
  backend:
    container_name: finpong-backend
    build: ./backend
    ports: 
        - 3002:3002
        - 4000:4000
    networks:
        - finpong-internal
  frontend:
    container_name: finpong-frontend
    build: ./frontend
    ports:
        - 3000:3000
    depends_on:
        - backend
    networks:
        - finpong-internal
  nginx:
    container_name: finpong-nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/sites-available:/etc/nginx/conf.d
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - finpong-internal
networks:
    finpong-internal: